version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    env_file:
      - ./.env
    tty: true
    depends_on:
      - backend
  
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    restart: always
    depends_on:
      - backend
      - db
      - frontend


volumes:
  postgres_data: