# Generated by Django 4.2.1 on 2023-06-03 16:19

import django.contrib.postgres.fields
import django.contrib.postgres.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), size=None, validators=[django.contrib.postgres.validators.ArrayMinLengthValidator(1)]),
        ),
    ]
